version: '3.4'

services:
  api: 
    build:
      context: .
      target: production
      
    ports:
      - 3001:3001

    environment:
      - MONOGODB_URL=<MONOGODB_URL>
      - NODE_ENV=production
      - PORT=3001
      - JWT_TOKEN=AngadRajSingh